### PR TITLE
AEA-2550 Use current timestamp as effectiveTime in cancellation requests

### PR DESCRIPTION
**Pull request by StefanoFrazzetto**

### CODE REVIEW

**Review by TomSmithCoding — COMMENTED** [review]
Changes to dateTime functionality looks good, wondering if the additions of `launch.json`, `settings.json` and changes in `package.json` are intentional. Are these related to the debugging functionality you mentioned yesterday?

**Comment by StefanoFrazzetto** [comment]
> Changes to dateTime functionality looks good, wondering if the additions of `launch.json`, `settings.json` and changes in `package.json` are intentional. Are these related to the debugging functionality you mentioned yesterday?

Yes, related to what I mentioned yesterday. I've added them to the PR to avoid forgetting about it

**Comment by TomSmithCoding** [comment]
> > Changes to dateTime functionality looks good, wondering if the additions of `launch.json`, `settings.json` and changes in `package.json` are intentional. Are these related to the debugging functionality you mentioned yesterday?
> 
> Yes, related to what I mentioned yesterday. I've added them to the PR to avoid forgetting about it

Ah right nice one, not sure what the team rule is on adding packages and such to the API so might want to have a thumbs up from Chris L or something before we merge that in. Other than that yeah works looking good.

**Review by TomSmithCoding — APPROVED** [review]

**Pull request merged**
